// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cnf.sql

package db

import (
	"context"
)

const getCnf = `-- name: GetCnf :one
SELECT 
    key, log
FROM    
    "cnf"
`

func (q *Queries) GetCnf(ctx context.Context) (Cnf, error) {
	row := q.db.QueryRowContext(ctx, getCnf)
	var i Cnf
	err := row.Scan(&i.Key, &i.Log)
	return i, err
}
